// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_invaild ValueType = 0
	ValueType_nil     ValueType = 1
	ValueType_string  ValueType = 2
	ValueType_int     ValueType = 3
	ValueType_uint    ValueType = 4
	ValueType_float   ValueType = 5
)

var ValueType_name = map[int32]string{
	0: "invaild",
	1: "nil",
	2: "string",
	3: "int",
	4: "uint",
	5: "float",
}
var ValueType_value = map[string]int32{
	"invaild": 0,
	"nil":     1,
	"string":  2,
	"int":     3,
	"uint":    4,
	"float":   5,
}

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}
func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (x *ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ValueType_value, data, "ValueType")
	if err != nil {
		return err
	}
	*x = ValueType(value)
	return nil
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{0}
}

type Value struct {
	Type                 *ValueType `protobuf:"varint,1,req,name=type,enum=proto.ValueType" json:"type,omitempty"`
	I                    *int64     `protobuf:"varint,2,opt,name=i" json:"i,omitempty"`
	U                    *uint64    `protobuf:"varint,3,opt,name=u" json:"u,omitempty"`
	F                    *float64   `protobuf:"fixed64,4,opt,name=f" json:"f,omitempty"`
	S                    *string    `protobuf:"bytes,5,opt,name=s" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{0}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetType() ValueType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ValueType_invaild
}

func (m *Value) GetI() int64 {
	if m != nil && m.I != nil {
		return *m.I
	}
	return 0
}

func (m *Value) GetU() uint64 {
	if m != nil && m.U != nil {
		return *m.U
	}
	return 0
}

func (m *Value) GetF() float64 {
	if m != nil && m.F != nil {
		return *m.F
	}
	return 0
}

func (m *Value) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

type Field struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	V                    *Value   `protobuf:"bytes,2,opt,name=v" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{1}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (dst *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(dst, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Field) GetV() *Value {
	if m != nil {
		return m.V
	}
	return nil
}

type PingReq struct {
	Timestamp            *int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{2}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (dst *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(dst, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PingResp struct {
	Timestamp            *int64   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{3}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (dst *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(dst, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

func (m *PingResp) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// 获取记录的指定字段
type GetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Fields               []string `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	Timeout              *int64   `protobuf:"varint,5,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{4}
}
func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (dst *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(dst, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GetReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *GetReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type GetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{5}
}
func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (dst *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(dst, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *GetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *GetResp) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

// 获取记录的所有字段
type GetAllReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Timeout              *int64   `protobuf:"varint,4,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllReq) Reset()         { *m = GetAllReq{} }
func (m *GetAllReq) String() string { return proto.CompactTextString(m) }
func (*GetAllReq) ProtoMessage()    {}
func (*GetAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{6}
}
func (m *GetAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllReq.Unmarshal(m, b)
}
func (m *GetAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllReq.Marshal(b, m, deterministic)
}
func (dst *GetAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllReq.Merge(dst, src)
}
func (m *GetAllReq) XXX_Size() int {
	return xxx_messageInfo_GetAllReq.Size(m)
}
func (m *GetAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllReq proto.InternalMessageInfo

func (m *GetAllReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetAllReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GetAllReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GetAllReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type GetAllResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResp) Reset()         { *m = GetAllResp{} }
func (m *GetAllResp) String() string { return proto.CompactTextString(m) }
func (*GetAllResp) ProtoMessage()    {}
func (*GetAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{7}
}
func (m *GetAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResp.Unmarshal(m, b)
}
func (m *GetAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResp.Marshal(b, m, deterministic)
}
func (dst *GetAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResp.Merge(dst, src)
}
func (m *GetAllResp) XXX_Size() int {
	return xxx_messageInfo_GetAllResp.Size(m)
}
func (m *GetAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResp proto.InternalMessageInfo

func (m *GetAllResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetAllResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *GetAllResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *GetAllResp) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

//
//  设置记录的指定字段，如果version被指定则只有当存储数据的版本号与指定的version一致时才执行设置
//  (注:未指定版本好的情况下，如果记录不存在则新增记录，新增记录时如果有未设定的字段，将会用设定的默认值初始化)
type SetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Version              *int64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Table                *string  `protobuf:"bytes,3,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields" json:"fields,omitempty"`
	Timeout              *int64   `protobuf:"varint,6,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReq) Reset()         { *m = SetReq{} }
func (m *SetReq) String() string { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()    {}
func (*SetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{8}
}
func (m *SetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReq.Unmarshal(m, b)
}
func (m *SetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReq.Marshal(b, m, deterministic)
}
func (dst *SetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReq.Merge(dst, src)
}
func (m *SetReq) XXX_Size() int {
	return xxx_messageInfo_SetReq.Size(m)
}
func (m *SetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetReq proto.InternalMessageInfo

func (m *SetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetReq) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *SetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *SetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SetReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type SetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResp) Reset()         { *m = SetResp{} }
func (m *SetResp) String() string { return proto.CompactTextString(m) }
func (*SetResp) ProtoMessage()    {}
func (*SetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{9}
}
func (m *SetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResp.Unmarshal(m, b)
}
func (m *SetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResp.Marshal(b, m, deterministic)
}
func (dst *SetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResp.Merge(dst, src)
}
func (m *SetResp) XXX_Size() int {
	return xxx_messageInfo_SetResp.Size(m)
}
func (m *SetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetResp proto.InternalMessageInfo

func (m *SetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

//
//  与set指令类似，只有当记录不存在时才能成功设置
type SetNxReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	Timeout              *int64   `protobuf:"varint,5,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNxReq) Reset()         { *m = SetNxReq{} }
func (m *SetNxReq) String() string { return proto.CompactTextString(m) }
func (*SetNxReq) ProtoMessage()    {}
func (*SetNxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{10}
}
func (m *SetNxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNxReq.Unmarshal(m, b)
}
func (m *SetNxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNxReq.Marshal(b, m, deterministic)
}
func (dst *SetNxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNxReq.Merge(dst, src)
}
func (m *SetNxReq) XXX_Size() int {
	return xxx_messageInfo_SetNxReq.Size(m)
}
func (m *SetNxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNxReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetNxReq proto.InternalMessageInfo

func (m *SetNxReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetNxReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *SetNxReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetNxReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *SetNxReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type SetNxResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNxResp) Reset()         { *m = SetNxResp{} }
func (m *SetNxResp) String() string { return proto.CompactTextString(m) }
func (*SetNxResp) ProtoMessage()    {}
func (*SetNxResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{11}
}
func (m *SetNxResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNxResp.Unmarshal(m, b)
}
func (m *SetNxResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNxResp.Marshal(b, m, deterministic)
}
func (dst *SetNxResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNxResp.Merge(dst, src)
}
func (m *SetNxResp) XXX_Size() int {
	return xxx_messageInfo_SetNxResp.Size(m)
}
func (m *SetNxResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNxResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetNxResp proto.InternalMessageInfo

func (m *SetNxResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetNxResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SetNxResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

//
//  将记录的field.name字段增加field.value,并返回增加后的值(field.value只支持int类型，如果记录不存在会用
//  记录的默认值初始化记录，int类型默认值为0，并在此基础上增加)
type IncrByReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Field                *Field   `protobuf:"bytes,4,req,name=field" json:"field,omitempty"`
	Timeout              *int64   `protobuf:"varint,5,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrByReq) Reset()         { *m = IncrByReq{} }
func (m *IncrByReq) String() string { return proto.CompactTextString(m) }
func (*IncrByReq) ProtoMessage()    {}
func (*IncrByReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{12}
}
func (m *IncrByReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrByReq.Unmarshal(m, b)
}
func (m *IncrByReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrByReq.Marshal(b, m, deterministic)
}
func (dst *IncrByReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrByReq.Merge(dst, src)
}
func (m *IncrByReq) XXX_Size() int {
	return xxx_messageInfo_IncrByReq.Size(m)
}
func (m *IncrByReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrByReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncrByReq proto.InternalMessageInfo

func (m *IncrByReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *IncrByReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *IncrByReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *IncrByReq) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *IncrByReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type IncrByResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	NewValue             *Field   `protobuf:"bytes,4,opt,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrByResp) Reset()         { *m = IncrByResp{} }
func (m *IncrByResp) String() string { return proto.CompactTextString(m) }
func (*IncrByResp) ProtoMessage()    {}
func (*IncrByResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{13}
}
func (m *IncrByResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrByResp.Unmarshal(m, b)
}
func (m *IncrByResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrByResp.Marshal(b, m, deterministic)
}
func (dst *IncrByResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrByResp.Merge(dst, src)
}
func (m *IncrByResp) XXX_Size() int {
	return xxx_messageInfo_IncrByResp.Size(m)
}
func (m *IncrByResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrByResp.DiscardUnknown(m)
}

var xxx_messageInfo_IncrByResp proto.InternalMessageInfo

func (m *IncrByResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *IncrByResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *IncrByResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *IncrByResp) GetNewValue() *Field {
	if m != nil {
		return m.NewValue
	}
	return nil
}

//
//  将记录的field.name字段减少field.value,并返回减少后的值(field.value只支持int类型，如果记录不存在会用
//  记录的默认值初始化记录，int类型默认值为0，并在此基础上减少)
type DecrByReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Field                *Field   `protobuf:"bytes,4,req,name=field" json:"field,omitempty"`
	Timeout              *int64   `protobuf:"varint,5,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrByReq) Reset()         { *m = DecrByReq{} }
func (m *DecrByReq) String() string { return proto.CompactTextString(m) }
func (*DecrByReq) ProtoMessage()    {}
func (*DecrByReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{14}
}
func (m *DecrByReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrByReq.Unmarshal(m, b)
}
func (m *DecrByReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrByReq.Marshal(b, m, deterministic)
}
func (dst *DecrByReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrByReq.Merge(dst, src)
}
func (m *DecrByReq) XXX_Size() int {
	return xxx_messageInfo_DecrByReq.Size(m)
}
func (m *DecrByReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrByReq.DiscardUnknown(m)
}

var xxx_messageInfo_DecrByReq proto.InternalMessageInfo

func (m *DecrByReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DecrByReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *DecrByReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *DecrByReq) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (m *DecrByReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type DecrByResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	NewValue             *Field   `protobuf:"bytes,4,opt,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrByResp) Reset()         { *m = DecrByResp{} }
func (m *DecrByResp) String() string { return proto.CompactTextString(m) }
func (*DecrByResp) ProtoMessage()    {}
func (*DecrByResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{15}
}
func (m *DecrByResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrByResp.Unmarshal(m, b)
}
func (m *DecrByResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrByResp.Marshal(b, m, deterministic)
}
func (dst *DecrByResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrByResp.Merge(dst, src)
}
func (m *DecrByResp) XXX_Size() int {
	return xxx_messageInfo_DecrByResp.Size(m)
}
func (m *DecrByResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrByResp.DiscardUnknown(m)
}

var xxx_messageInfo_DecrByResp proto.InternalMessageInfo

func (m *DecrByResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DecrByResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *DecrByResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *DecrByResp) GetNewValue() *Field {
	if m != nil {
		return m.NewValue
	}
	return nil
}

//
//  如果记录存在且old.name的值与old.value相等，将其设定为new.value
//  只要记录存在，无论替换是否成功都将返回old.name的当前值。
type CompareAndSetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	New                  *Field   `protobuf:"bytes,4,req,name=new" json:"new,omitempty"`
	Old                  *Field   `protobuf:"bytes,5,req,name=old" json:"old,omitempty"`
	Timeout              *int64   `protobuf:"varint,6,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetReq) Reset()         { *m = CompareAndSetReq{} }
func (m *CompareAndSetReq) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetReq) ProtoMessage()    {}
func (*CompareAndSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{16}
}
func (m *CompareAndSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetReq.Unmarshal(m, b)
}
func (m *CompareAndSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetReq.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetReq.Merge(dst, src)
}
func (m *CompareAndSetReq) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetReq.Size(m)
}
func (m *CompareAndSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetReq proto.InternalMessageInfo

func (m *CompareAndSetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *CompareAndSetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CompareAndSetReq) GetNew() *Field {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *CompareAndSetReq) GetOld() *Field {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *CompareAndSetReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type CompareAndSetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Value                *Field   `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetResp) Reset()         { *m = CompareAndSetResp{} }
func (m *CompareAndSetResp) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetResp) ProtoMessage()    {}
func (*CompareAndSetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{17}
}
func (m *CompareAndSetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetResp.Unmarshal(m, b)
}
func (m *CompareAndSetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetResp.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetResp.Merge(dst, src)
}
func (m *CompareAndSetResp) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetResp.Size(m)
}
func (m *CompareAndSetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetResp proto.InternalMessageInfo

func (m *CompareAndSetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CompareAndSetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CompareAndSetResp) GetValue() *Field {
	if m != nil {
		return m.Value
	}
	return nil
}

//
//  如果记录不存在，或old.name的值与old.value相等，将其设定为new.value
//  无论替换是否成功都将返回old.name的当前值。(注意:如果记录不存在，old.name以外的字段将被设置为初始值)
type CompareAndSetNxReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	New                  *Field   `protobuf:"bytes,4,req,name=new" json:"new,omitempty"`
	Old                  *Field   `protobuf:"bytes,5,req,name=old" json:"old,omitempty"`
	Timeout              *int64   `protobuf:"varint,6,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetNxReq) Reset()         { *m = CompareAndSetNxReq{} }
func (m *CompareAndSetNxReq) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetNxReq) ProtoMessage()    {}
func (*CompareAndSetNxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{18}
}
func (m *CompareAndSetNxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetNxReq.Unmarshal(m, b)
}
func (m *CompareAndSetNxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetNxReq.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetNxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetNxReq.Merge(dst, src)
}
func (m *CompareAndSetNxReq) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetNxReq.Size(m)
}
func (m *CompareAndSetNxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetNxReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetNxReq proto.InternalMessageInfo

func (m *CompareAndSetNxReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetNxReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *CompareAndSetNxReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CompareAndSetNxReq) GetNew() *Field {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *CompareAndSetNxReq) GetOld() *Field {
	if m != nil {
		return m.Old
	}
	return nil
}

func (m *CompareAndSetNxReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type CompareAndSetNxResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Value                *Field   `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetNxResp) Reset()         { *m = CompareAndSetNxResp{} }
func (m *CompareAndSetNxResp) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetNxResp) ProtoMessage()    {}
func (*CompareAndSetNxResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{19}
}
func (m *CompareAndSetNxResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetNxResp.Unmarshal(m, b)
}
func (m *CompareAndSetNxResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetNxResp.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetNxResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetNxResp.Merge(dst, src)
}
func (m *CompareAndSetNxResp) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetNxResp.Size(m)
}
func (m *CompareAndSetNxResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetNxResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetNxResp proto.InternalMessageInfo

func (m *CompareAndSetNxResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetNxResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CompareAndSetNxResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CompareAndSetNxResp) GetValue() *Field {
	if m != nil {
		return m.Value
	}
	return nil
}

// 删除命令(只支持删除整个记录，不支持删除记录的字段)
type DelReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Version              *int64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Table                *string  `protobuf:"bytes,3,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	Timeout              *int64   `protobuf:"varint,5,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{20}
}
func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (dst *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(dst, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DelReq) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *DelReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *DelReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *DelReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type DelResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResp) Reset()         { *m = DelResp{} }
func (m *DelResp) String() string { return proto.CompactTextString(m) }
func (*DelResp) ProtoMessage()    {}
func (*DelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{21}
}
func (m *DelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResp.Unmarshal(m, b)
}
func (m *DelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResp.Marshal(b, m, deterministic)
}
func (dst *DelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResp.Merge(dst, src)
}
func (m *DelResp) XXX_Size() int {
	return xxx_messageInfo_DelResp.Size(m)
}
func (m *DelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelResp proto.InternalMessageInfo

func (m *DelResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DelResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *DelResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type Row struct {
	Fields               []*Field `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{22}
}
func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (dst *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(dst, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ScanReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	Fields               []string `protobuf:"bytes,3,rep,name=fields" json:"fields,omitempty"`
	All                  *int32   `protobuf:"varint,4,opt,name=all" json:"all,omitempty"`
	Count                *int32   `protobuf:"varint,5,opt,name=count" json:"count,omitempty"`
	Timeout              *int64   `protobuf:"varint,6,req,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanReq) Reset()         { *m = ScanReq{} }
func (m *ScanReq) String() string { return proto.CompactTextString(m) }
func (*ScanReq) ProtoMessage()    {}
func (*ScanReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{23}
}
func (m *ScanReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanReq.Unmarshal(m, b)
}
func (m *ScanReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanReq.Marshal(b, m, deterministic)
}
func (dst *ScanReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanReq.Merge(dst, src)
}
func (m *ScanReq) XXX_Size() int {
	return xxx_messageInfo_ScanReq.Size(m)
}
func (m *ScanReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanReq.DiscardUnknown(m)
}

var xxx_messageInfo_ScanReq proto.InternalMessageInfo

func (m *ScanReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *ScanReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *ScanReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ScanReq) GetAll() int32 {
	if m != nil && m.All != nil {
		return *m.All
	}
	return 0
}

func (m *ScanReq) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *ScanReq) GetTimeout() int64 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type ScanResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Rows                 []*Row   `protobuf:"bytes,3,rep,name=rows" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanResp) Reset()         { *m = ScanResp{} }
func (m *ScanResp) String() string { return proto.CompactTextString(m) }
func (*ScanResp) ProtoMessage()    {}
func (*ScanResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_46138e5b811320cd, []int{24}
}
func (m *ScanResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResp.Unmarshal(m, b)
}
func (m *ScanResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResp.Marshal(b, m, deterministic)
}
func (dst *ScanResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResp.Merge(dst, src)
}
func (m *ScanResp) XXX_Size() int {
	return xxx_messageInfo_ScanResp.Size(m)
}
func (m *ScanResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResp.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResp proto.InternalMessageInfo

func (m *ScanResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *ScanResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *ScanResp) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "proto.value")
	proto.RegisterType((*Field)(nil), "proto.field")
	proto.RegisterType((*PingReq)(nil), "proto.ping_req")
	proto.RegisterType((*PingResp)(nil), "proto.ping_resp")
	proto.RegisterType((*GetReq)(nil), "proto.get_req")
	proto.RegisterType((*GetResp)(nil), "proto.get_resp")
	proto.RegisterType((*GetAllReq)(nil), "proto.get_all_req")
	proto.RegisterType((*GetAllResp)(nil), "proto.get_all_resp")
	proto.RegisterType((*SetReq)(nil), "proto.set_req")
	proto.RegisterType((*SetResp)(nil), "proto.set_resp")
	proto.RegisterType((*SetNxReq)(nil), "proto.set_nx_req")
	proto.RegisterType((*SetNxResp)(nil), "proto.set_nx_resp")
	proto.RegisterType((*IncrByReq)(nil), "proto.incr_by_req")
	proto.RegisterType((*IncrByResp)(nil), "proto.incr_by_resp")
	proto.RegisterType((*DecrByReq)(nil), "proto.decr_by_req")
	proto.RegisterType((*DecrByResp)(nil), "proto.decr_by_resp")
	proto.RegisterType((*CompareAndSetReq)(nil), "proto.compare_and_set_req")
	proto.RegisterType((*CompareAndSetResp)(nil), "proto.compare_and_set_resp")
	proto.RegisterType((*CompareAndSetNxReq)(nil), "proto.compare_and_set_nx_req")
	proto.RegisterType((*CompareAndSetNxResp)(nil), "proto.compare_and_set_nx_resp")
	proto.RegisterType((*DelReq)(nil), "proto.del_req")
	proto.RegisterType((*DelResp)(nil), "proto.del_resp")
	proto.RegisterType((*Row)(nil), "proto.row")
	proto.RegisterType((*ScanReq)(nil), "proto.scan_req")
	proto.RegisterType((*ScanResp)(nil), "proto.scan_resp")
	proto.RegisterEnum("proto.ValueType", ValueType_name, ValueType_value)
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_proto_46138e5b811320cd) }

var fileDescriptor_proto_46138e5b811320cd = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x6f, 0xd3, 0x3c,
	0x18, 0x7f, 0x1d, 0x27, 0x4b, 0xf2, 0xa4, 0x7a, 0x15, 0x99, 0x69, 0x44, 0x08, 0x4d, 0x51, 0xb4,
	0x43, 0x00, 0x69, 0x87, 0x5d, 0xf8, 0x00, 0x1c, 0xb9, 0x59, 0x13, 0x1c, 0x38, 0x54, 0x59, 0xe3,
	0x56, 0x11, 0xa9, 0x9d, 0xc5, 0x69, 0x4b, 0x41, 0xe2, 0x80, 0x90, 0x10, 0x9c, 0xf8, 0x0a, 0x7c,
	0x00, 0x24, 0x3e, 0x22, 0xb2, 0x93, 0x36, 0x4d, 0xd7, 0x56, 0x13, 0xca, 0x18, 0x97, 0xd6, 0xcf,
	0xf3, 0xb8, 0xfe, 0xfd, 0xb1, 0xfb, 0xd8, 0xe0, 0x15, 0xa5, 0xa8, 0xc4, 0xb9, 0xfe, 0x24, 0x96,
	0xfe, 0x8a, 0x18, 0x58, 0xf3, 0x24, 0x9f, 0x31, 0x72, 0x06, 0x66, 0xb5, 0x2c, 0x58, 0x80, 0x42,
	0x23, 0xfe, 0xff, 0xc2, 0xaf, 0x67, 0x9d, 0xbf, 0x52, 0xb5, 0xcb, 0x65, 0xc1, 0xa8, 0xae, 0x92,
	0x01, 0xa0, 0x2c, 0x30, 0x42, 0x14, 0x63, 0x8a, 0x32, 0x15, 0xcd, 0x02, 0x1c, 0xa2, 0xd8, 0xa4,
	0x68, 0xa6, 0xa2, 0x71, 0x60, 0x86, 0x28, 0x46, 0x14, 0x8d, 0x55, 0x24, 0x03, 0x2b, 0x44, 0xb1,
	0x4b, 0x91, 0x8c, 0x9e, 0x83, 0x35, 0xce, 0x58, 0x9e, 0x12, 0x02, 0x26, 0x4f, 0xa6, 0x0a, 0x46,
	0x55, 0xf4, 0x98, 0x3c, 0x02, 0x34, 0xd7, 0x8b, 0x7a, 0x17, 0x83, 0x06, 0x57, 0x73, 0xa2, 0x68,
	0x1e, 0xc5, 0xe0, 0x14, 0x19, 0x9f, 0x0c, 0x4b, 0x76, 0x4d, 0x1e, 0x83, 0x5b, 0x65, 0x53, 0x26,
	0xab, 0x64, 0x5a, 0xe8, 0x05, 0x30, 0x6d, 0x13, 0xd1, 0x13, 0x70, 0x9b, 0x99, 0xb2, 0xe8, 0x4e,
	0x35, 0xb6, 0xa7, 0x2e, 0xc1, 0x9e, 0xb0, 0x4a, 0xaf, 0x79, 0x0c, 0x96, 0x64, 0xd7, 0x5c, 0x68,
	0xdd, 0x98, 0xd6, 0x81, 0xca, 0x56, 0xc9, 0x55, 0xce, 0x02, 0x23, 0x34, 0x62, 0x97, 0xd6, 0x01,
	0xf1, 0x01, 0xbf, 0x65, 0xcb, 0x00, 0xeb, 0x9c, 0x1a, 0x92, 0x13, 0x38, 0xd2, 0xb2, 0x64, 0x60,
	0x86, 0x38, 0x76, 0x69, 0x13, 0x91, 0x00, 0x6c, 0x85, 0x26, 0x66, 0x55, 0x60, 0xe9, 0x75, 0x57,
	0x61, 0xf4, 0x1e, 0x9c, 0x1a, 0x5a, 0x16, 0x7b, 0xb0, 0x03, 0xb0, 0x59, 0x59, 0xbe, 0x10, 0x69,
	0x8d, 0x6e, 0xd1, 0x55, 0xa8, 0x2a, 0x73, 0x56, 0xca, 0x4c, 0x70, 0x6d, 0x3a, 0xa6, 0xab, 0x90,
	0x9c, 0x75, 0x78, 0xb4, 0x36, 0xea, 0xe4, 0x8a, 0x55, 0xc4, 0xc0, 0x53, 0xd8, 0x49, 0x9e, 0xf7,
	0x20, 0x7d, 0x43, 0xa2, 0xd9, 0x95, 0xf8, 0x11, 0x06, 0x2d, 0xcc, 0x3d, 0xc8, 0xfc, 0x81, 0xc0,
	0x96, 0x07, 0xb7, 0x77, 0x03, 0xc1, 0xe8, 0x22, 0xac, 0xd5, 0xe3, 0x1d, 0xea, 0xcd, 0x56, 0x7d,
	0xcb, 0xc4, 0xda, 0xcf, 0x64, 0xd3, 0xa3, 0xa3, 0xae, 0x47, 0x97, 0xe0, 0xc8, 0xde, 0x8f, 0x41,
	0xf4, 0x0d, 0x01, 0xa8, 0x65, 0xf9, 0xbb, 0x1e, 0x36, 0xf8, 0x56, 0x66, 0x1f, 0x38, 0xe9, 0xaf,
	0xc1, 0x5b, 0x73, 0xe9, 0x55, 0xe5, 0x57, 0x04, 0x5e, 0xc6, 0x47, 0xe5, 0xf0, 0x6a, 0xd9, 0x83,
	0xcc, 0xa8, 0xe9, 0x4c, 0x7a, 0x77, 0xb7, 0x55, 0x36, 0x4d, 0x6b, 0xbf, 0xc8, 0x4f, 0x08, 0x06,
	0x2d, 0x97, 0x5e, 0x0f, 0x7b, 0x0c, 0x0e, 0x67, 0x0b, 0xdd, 0x80, 0x75, 0x57, 0xdd, 0xe6, 0xb6,
	0xae, 0x6a, 0x43, 0x52, 0xf6, 0xef, 0x18, 0xd2, 0x72, 0xb9, 0x27, 0x43, 0x7e, 0x22, 0x78, 0x30,
	0x12, 0xd3, 0x22, 0x29, 0xd9, 0x30, 0xe1, 0xe9, 0x50, 0xf6, 0xd2, 0xec, 0x4f, 0x01, 0x73, 0xb6,
	0xd8, 0x69, 0x8b, 0x2a, 0xa8, 0xba, 0xc8, 0x53, 0x6d, 0xc8, 0x8d, 0xba, 0xe8, 0x9a, 0xb6, 0xd5,
	0x0d, 0x3e, 0x23, 0x38, 0xbe, 0xc9, 0xb7, 0x57, 0xf3, 0xa2, 0xe6, 0x9e, 0xdf, 0xe9, 0x5c, 0x5d,
	0x8a, 0x7e, 0x21, 0x38, 0xd9, 0xa6, 0xd1, 0x4b, 0x2b, 0xb9, 0x3b, 0xe7, 0xbe, 0x20, 0x78, 0xb8,
	0x93, 0xf2, 0x5f, 0x37, 0xef, 0x03, 0xd8, 0x29, 0xcb, 0xef, 0xf4, 0xd2, 0xd9, 0xff, 0xaf, 0xbb,
	0x04, 0xa7, 0x06, 0xef, 0xb5, 0xd1, 0x3e, 0x03, 0x5c, 0x8a, 0xc5, 0xc6, 0x45, 0x80, 0x0e, 0xdc,
	0xba, 0xdf, 0x11, 0x38, 0x72, 0x94, 0xf0, 0xdb, 0x1d, 0x17, 0xd4, 0xea, 0x6c, 0xdf, 0x50, 0xb8,
	0xf3, 0x86, 0xf2, 0x01, 0x27, 0x79, 0xae, 0x2d, 0xb7, 0xa8, 0x1a, 0xaa, 0xdf, 0x8f, 0xc4, 0x8c,
	0x57, 0xfa, 0x59, 0x69, 0xd1, 0x3a, 0x38, 0x70, 0x38, 0xde, 0x80, 0xdb, 0x30, 0xfa, 0x03, 0x5b,
	0x4e, 0xc1, 0x2c, 0xc5, 0xa2, 0x26, 0xe5, 0x5d, 0x40, 0xa3, 0xb9, 0x14, 0x0b, 0xaa, 0xf3, 0x4f,
	0x5f, 0x82, 0xbb, 0x7e, 0x1c, 0x13, 0x0f, 0xec, 0x8c, 0xcf, 0x93, 0x2c, 0x4f, 0xfd, 0xff, 0x88,
	0x0d, 0x98, 0x67, 0xb9, 0x8f, 0x08, 0xc0, 0x91, 0xac, 0xca, 0x8c, 0x4f, 0x7c, 0x43, 0x25, 0x33,
	0x5e, 0xf9, 0x98, 0x38, 0x60, 0xce, 0xd4, 0xc8, 0x24, 0x2e, 0x58, 0xe3, 0x5c, 0x24, 0x95, 0x6f,
	0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xb5, 0xc0, 0xd4, 0x9a, 0x0b, 0x00, 0x00,
}
