// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_Nil      ValueType = 1
	ValueType_String   ValueType = 2
	ValueType_Integer  ValueType = 3
	ValueType_Uinteger ValueType = 4
	ValueType_Float    ValueType = 5
	ValueType_Invaild  ValueType = 6
)

var ValueType_name = map[int32]string{
	1: "Nil",
	2: "String",
	3: "Integer",
	4: "Uinteger",
	5: "Float",
	6: "Invaild",
}
var ValueType_value = map[string]int32{
	"Nil":      1,
	"String":   2,
	"Integer":  3,
	"Uinteger": 4,
	"Float":    5,
	"Invaild":  6,
}

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}
func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (x *ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ValueType_value, data, "ValueType")
	if err != nil {
		return err
	}
	*x = ValueType(value)
	return nil
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{0}
}

type Value struct {
	Tt                   *ValueType `protobuf:"varint,1,req,name=tt,enum=proto.ValueType" json:"tt,omitempty"`
	VInt                 *int64     `protobuf:"varint,2,opt,name=vInt" json:"vInt,omitempty"`
	VUInt                *uint64    `protobuf:"varint,3,opt,name=vUInt" json:"vUInt,omitempty"`
	VFloat               *float64   `protobuf:"fixed64,4,opt,name=vFloat" json:"vFloat,omitempty"`
	VString              *string    `protobuf:"bytes,5,opt,name=vString" json:"vString,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{0}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetTt() ValueType {
	if m != nil && m.Tt != nil {
		return *m.Tt
	}
	return ValueType_Nil
}

func (m *Value) GetVInt() int64 {
	if m != nil && m.VInt != nil {
		return *m.VInt
	}
	return 0
}

func (m *Value) GetVUInt() uint64 {
	if m != nil && m.VUInt != nil {
		return *m.VUInt
	}
	return 0
}

func (m *Value) GetVFloat() float64 {
	if m != nil && m.VFloat != nil {
		return *m.VFloat
	}
	return 0
}

func (m *Value) GetVString() string {
	if m != nil && m.VString != nil {
		return *m.VString
	}
	return ""
}

type Field struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	V                    *Value   `protobuf:"bytes,2,opt,name=v" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{1}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (dst *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(dst, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Field) GetV() *Value {
	if m != nil {
		return m.V
	}
	return nil
}

type PingReq struct {
	Timestamp            *int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{2}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (dst *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(dst, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PingResp struct {
	Timestamp            *int64   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{3}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (dst *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(dst, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

func (m *PingResp) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type DelReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Version              *int64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Table                *string  `protobuf:"bytes,3,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{4}
}
func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (dst *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(dst, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DelReq) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *DelReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *DelReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type DelResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResp) Reset()         { *m = DelResp{} }
func (m *DelResp) String() string { return proto.CompactTextString(m) }
func (*DelResp) ProtoMessage()    {}
func (*DelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{5}
}
func (m *DelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResp.Unmarshal(m, b)
}
func (m *DelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResp.Marshal(b, m, deterministic)
}
func (dst *DelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResp.Merge(dst, src)
}
func (m *DelResp) XXX_Size() int {
	return xxx_messageInfo_DelResp.Size(m)
}
func (m *DelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelResp proto.InternalMessageInfo

func (m *DelResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DelResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

type SetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Version              *int64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Table                *string  `protobuf:"bytes,3,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReq) Reset()         { *m = SetReq{} }
func (m *SetReq) String() string { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()    {}
func (*SetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{6}
}
func (m *SetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReq.Unmarshal(m, b)
}
func (m *SetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReq.Marshal(b, m, deterministic)
}
func (dst *SetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReq.Merge(dst, src)
}
func (m *SetReq) XXX_Size() int {
	return xxx_messageInfo_SetReq.Size(m)
}
func (m *SetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetReq proto.InternalMessageInfo

func (m *SetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetReq) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *SetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *SetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResp) Reset()         { *m = SetResp{} }
func (m *SetResp) String() string { return proto.CompactTextString(m) }
func (*SetResp) ProtoMessage()    {}
func (*SetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{7}
}
func (m *SetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResp.Unmarshal(m, b)
}
func (m *SetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResp.Marshal(b, m, deterministic)
}
func (dst *SetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResp.Merge(dst, src)
}
func (m *SetResp) XXX_Size() int {
	return xxx_messageInfo_SetResp.Size(m)
}
func (m *SetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetResp proto.InternalMessageInfo

func (m *SetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type GetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Fields               []string `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{8}
}
func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (dst *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(dst, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GetReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_9a1e1ae5ea94a8db, []int{9}
}
func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (dst *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(dst, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *GetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *GetResp) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "proto.value")
	proto.RegisterType((*Field)(nil), "proto.field")
	proto.RegisterType((*PingReq)(nil), "proto.ping_req")
	proto.RegisterType((*PingResp)(nil), "proto.ping_resp")
	proto.RegisterType((*DelReq)(nil), "proto.del_req")
	proto.RegisterType((*DelResp)(nil), "proto.del_resp")
	proto.RegisterType((*SetReq)(nil), "proto.set_req")
	proto.RegisterType((*SetResp)(nil), "proto.set_resp")
	proto.RegisterType((*GetReq)(nil), "proto.get_req")
	proto.RegisterType((*GetResp)(nil), "proto.get_resp")
	proto.RegisterEnum("proto.ValueType", ValueType_name, ValueType_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_9a1e1ae5ea94a8db) }

var fileDescriptor_protocol_9a1e1ae5ea94a8db = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x6b, 0xd5, 0x40,
	0x10, 0x66, 0x77, 0xb3, 0x2f, 0xc9, 0xb4, 0x94, 0x30, 0x94, 0xb2, 0x88, 0x87, 0x25, 0x78, 0x58,
	0x3d, 0xf4, 0xd0, 0x8b, 0xe0, 0x55, 0x10, 0x7a, 0xf1, 0xb0, 0x6d, 0xbd, 0x96, 0xe8, 0x1b, 0x43,
	0x30, 0x2f, 0x49, 0x93, 0x75, 0xa1, 0xde, 0xc5, 0xbf, 0x2d, 0xd9, 0xcd, 0x4b, 0x5f, 0xc5, 0x0a,
	0x82, 0x9e, 0x32, 0xdf, 0xcc, 0x97, 0x99, 0xef, 0x9b, 0x65, 0xe0, 0x64, 0x18, 0x7b, 0xd7, 0x7f,
	0xea, 0xdb, 0xf3, 0x10, 0xa0, 0x0c, 0x9f, 0xf2, 0x3b, 0x03, 0xe9, 0xab, 0xf6, 0x2b, 0xa1, 0x06,
	0xee, 0x9c, 0x62, 0x9a, 0x9b, 0x93, 0x8b, 0x22, 0x92, 0xce, 0x3f, 0xcc, 0x95, 0xeb, 0xfb, 0x81,
	0x2c, 0x77, 0x0e, 0x11, 0x12, 0x7f, 0xd9, 0x39, 0xc5, 0x35, 0x33, 0xc2, 0x86, 0x18, 0x4f, 0x41,
	0xfa, 0x9b, 0x39, 0x29, 0x34, 0x33, 0x89, 0x8d, 0x00, 0xcf, 0x60, 0xe3, 0xdf, 0xb5, 0x7d, 0xe5,
	0x54, 0xa2, 0x99, 0x61, 0x76, 0x41, 0xa8, 0x20, 0xf5, 0x57, 0x6e, 0x6c, 0xba, 0x5a, 0x49, 0xcd,
	0x4c, 0x6e, 0xf7, 0xb0, 0x7c, 0x0d, 0xf2, 0x73, 0x43, 0xed, 0x76, 0x1e, 0xd2, 0x55, 0x3b, 0x52,
	0x2c, 0xd4, 0x43, 0x8c, 0xcf, 0x80, 0xf9, 0x30, 0xf5, 0xe8, 0xe2, 0x78, 0x51, 0x16, 0x34, 0x5b,
	0xe6, 0x4b, 0x03, 0xd9, 0xd0, 0x74, 0xf5, 0xed, 0x48, 0x77, 0xf8, 0x1c, 0x72, 0xd7, 0xec, 0x68,
	0x72, 0xd5, 0x6e, 0x08, 0x0d, 0x84, 0x7d, 0x48, 0x94, 0x2f, 0x21, 0x5f, 0x98, 0xd3, 0xf0, 0x98,
	0xca, 0x7f, 0xa5, 0x56, 0x90, 0x6e, 0xa9, 0x0d, 0x3d, 0x4f, 0x41, 0x4e, 0x74, 0xd7, 0xf5, 0x61,
	0x33, 0xc2, 0x46, 0x10, 0x8c, 0xd0, 0x38, 0x35, 0x7d, 0xb7, 0xfc, 0xbc, 0x87, 0x33, 0xdf, 0x55,
	0x1f, 0x5b, 0x52, 0x42, 0x73, 0x93, 0xdb, 0x08, 0xb0, 0x00, 0xf1, 0x85, 0xee, 0x55, 0x12, 0x72,
	0x73, 0x58, 0xbe, 0x81, 0x2c, 0x8e, 0x98, 0x86, 0xa7, 0x67, 0xd0, 0x38, 0xbe, 0xed, 0xb7, 0xa4,
	0xb8, 0xe6, 0x46, 0xda, 0x3d, 0x2c, 0x7f, 0x30, 0x48, 0x27, 0x72, 0xff, 0x53, 0x1f, 0xbe, 0x80,
	0x4d, 0x78, 0x90, 0x49, 0x49, 0x2d, 0x0e, 0x16, 0x1f, 0x92, 0x76, 0xa9, 0x95, 0xd7, 0x90, 0x45,
	0x21, 0x7f, 0xef, 0xe2, 0x50, 0xa3, 0x78, 0xa4, 0xb1, 0xbc, 0x85, 0xb4, 0xfe, 0xa3, 0xbd, 0xd5,
	0x04, 0xff, 0x8d, 0x09, 0xf1, 0x60, 0xe2, 0x6c, 0x35, 0x91, 0x68, 0x61, 0xf2, 0x55, 0xf6, 0x37,
	0xc8, 0xea, 0x7f, 0x2e, 0xfb, 0x60, 0x65, 0xc9, 0xd3, 0x2b, 0x7b, 0x75, 0x05, 0xf9, 0x7a, 0x56,
	0x98, 0x82, 0x78, 0xdf, 0xb4, 0x05, 0x43, 0x80, 0x4d, 0xbc, 0x84, 0x82, 0xe3, 0x11, 0xa4, 0x97,
	0x9d, 0xa3, 0x9a, 0xc6, 0x42, 0xe0, 0x31, 0x64, 0x37, 0xcd, 0x82, 0x12, 0xcc, 0x41, 0x86, 0x4b,
	0x2a, 0x64, 0x64, 0xf9, 0xaa, 0x69, 0xb7, 0xc5, 0xe6, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x22, 0x45, 0x5d, 0xde, 0x03, 0x00, 0x00,
}
