// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ValueType int32

const (
	ValueType_Nil      ValueType = 1
	ValueType_String   ValueType = 2
	ValueType_Integer  ValueType = 3
	ValueType_Uinteger ValueType = 4
	ValueType_Float    ValueType = 5
	ValueType_Invaild  ValueType = 6
)

var ValueType_name = map[int32]string{
	1: "Nil",
	2: "String",
	3: "Integer",
	4: "Uinteger",
	5: "Float",
	6: "Invaild",
}
var ValueType_value = map[string]int32{
	"Nil":      1,
	"String":   2,
	"Integer":  3,
	"Uinteger": 4,
	"Float":    5,
	"Invaild":  6,
}

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}
func (x ValueType) String() string {
	return proto.EnumName(ValueType_name, int32(x))
}
func (x *ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ValueType_value, data, "ValueType")
	if err != nil {
		return err
	}
	*x = ValueType(value)
	return nil
}
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{0}
}

type Value struct {
	Tt                   *ValueType `protobuf:"varint,1,req,name=tt,enum=proto.ValueType" json:"tt,omitempty"`
	VInt                 *int64     `protobuf:"varint,2,opt,name=vInt" json:"vInt,omitempty"`
	VUInt                *uint64    `protobuf:"varint,3,opt,name=vUInt" json:"vUInt,omitempty"`
	VFloat               *float64   `protobuf:"fixed64,4,opt,name=vFloat" json:"vFloat,omitempty"`
	VString              *string    `protobuf:"bytes,5,opt,name=vString" json:"vString,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{0}
}
func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (dst *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(dst, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

func (m *Value) GetTt() ValueType {
	if m != nil && m.Tt != nil {
		return *m.Tt
	}
	return ValueType_Nil
}

func (m *Value) GetVInt() int64 {
	if m != nil && m.VInt != nil {
		return *m.VInt
	}
	return 0
}

func (m *Value) GetVUInt() uint64 {
	if m != nil && m.VUInt != nil {
		return *m.VUInt
	}
	return 0
}

func (m *Value) GetVFloat() float64 {
	if m != nil && m.VFloat != nil {
		return *m.VFloat
	}
	return 0
}

func (m *Value) GetVString() string {
	if m != nil && m.VString != nil {
		return *m.VString
	}
	return ""
}

type Field struct {
	Name                 *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	V                    *Value   `protobuf:"bytes,2,opt,name=v" json:"v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{1}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (dst *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(dst, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Field) GetV() *Value {
	if m != nil {
		return m.V
	}
	return nil
}

type PingReq struct {
	Timestamp            *int64   `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingReq) Reset()         { *m = PingReq{} }
func (m *PingReq) String() string { return proto.CompactTextString(m) }
func (*PingReq) ProtoMessage()    {}
func (*PingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{2}
}
func (m *PingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingReq.Unmarshal(m, b)
}
func (m *PingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingReq.Marshal(b, m, deterministic)
}
func (dst *PingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingReq.Merge(dst, src)
}
func (m *PingReq) XXX_Size() int {
	return xxx_messageInfo_PingReq.Size(m)
}
func (m *PingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PingReq.DiscardUnknown(m)
}

var xxx_messageInfo_PingReq proto.InternalMessageInfo

func (m *PingReq) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type PingResp struct {
	Timestamp            *int64   `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResp) Reset()         { *m = PingResp{} }
func (m *PingResp) String() string { return proto.CompactTextString(m) }
func (*PingResp) ProtoMessage()    {}
func (*PingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{3}
}
func (m *PingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResp.Unmarshal(m, b)
}
func (m *PingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResp.Marshal(b, m, deterministic)
}
func (dst *PingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResp.Merge(dst, src)
}
func (m *PingResp) XXX_Size() int {
	return xxx_messageInfo_PingResp.Size(m)
}
func (m *PingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResp.DiscardUnknown(m)
}

var xxx_messageInfo_PingResp proto.InternalMessageInfo

func (m *PingResp) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type DelReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Version              *int64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Table                *string  `protobuf:"bytes,3,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelReq) Reset()         { *m = DelReq{} }
func (m *DelReq) String() string { return proto.CompactTextString(m) }
func (*DelReq) ProtoMessage()    {}
func (*DelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{4}
}
func (m *DelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelReq.Unmarshal(m, b)
}
func (m *DelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelReq.Marshal(b, m, deterministic)
}
func (dst *DelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelReq.Merge(dst, src)
}
func (m *DelReq) XXX_Size() int {
	return xxx_messageInfo_DelReq.Size(m)
}
func (m *DelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelReq proto.InternalMessageInfo

func (m *DelReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DelReq) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *DelReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *DelReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type DelResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResp) Reset()         { *m = DelResp{} }
func (m *DelResp) String() string { return proto.CompactTextString(m) }
func (*DelResp) ProtoMessage()    {}
func (*DelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{5}
}
func (m *DelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResp.Unmarshal(m, b)
}
func (m *DelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResp.Marshal(b, m, deterministic)
}
func (dst *DelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResp.Merge(dst, src)
}
func (m *DelResp) XXX_Size() int {
	return xxx_messageInfo_DelResp.Size(m)
}
func (m *DelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResp.DiscardUnknown(m)
}

var xxx_messageInfo_DelResp proto.InternalMessageInfo

func (m *DelResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DelResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

type SetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Version              *int64   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	Table                *string  `protobuf:"bytes,3,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,4,req,name=key" json:"key,omitempty"`
	Fields               []*Field `protobuf:"bytes,5,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetReq) Reset()         { *m = SetReq{} }
func (m *SetReq) String() string { return proto.CompactTextString(m) }
func (*SetReq) ProtoMessage()    {}
func (*SetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{6}
}
func (m *SetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetReq.Unmarshal(m, b)
}
func (m *SetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetReq.Marshal(b, m, deterministic)
}
func (dst *SetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetReq.Merge(dst, src)
}
func (m *SetReq) XXX_Size() int {
	return xxx_messageInfo_SetReq.Size(m)
}
func (m *SetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetReq proto.InternalMessageInfo

func (m *SetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetReq) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *SetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *SetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResp) Reset()         { *m = SetResp{} }
func (m *SetResp) String() string { return proto.CompactTextString(m) }
func (*SetResp) ProtoMessage()    {}
func (*SetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{7}
}
func (m *SetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResp.Unmarshal(m, b)
}
func (m *SetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResp.Marshal(b, m, deterministic)
}
func (dst *SetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResp.Merge(dst, src)
}
func (m *SetResp) XXX_Size() int {
	return xxx_messageInfo_SetResp.Size(m)
}
func (m *SetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetResp proto.InternalMessageInfo

func (m *SetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type GetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Fields               []string `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReq) Reset()         { *m = GetReq{} }
func (m *GetReq) String() string { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()    {}
func (*GetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{8}
}
func (m *GetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReq.Unmarshal(m, b)
}
func (m *GetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReq.Marshal(b, m, deterministic)
}
func (dst *GetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReq.Merge(dst, src)
}
func (m *GetReq) XXX_Size() int {
	return xxx_messageInfo_GetReq.Size(m)
}
func (m *GetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetReq proto.InternalMessageInfo

func (m *GetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *GetReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResp) Reset()         { *m = GetResp{} }
func (m *GetResp) String() string { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()    {}
func (*GetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{9}
}
func (m *GetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResp.Unmarshal(m, b)
}
func (m *GetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResp.Marshal(b, m, deterministic)
}
func (dst *GetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResp.Merge(dst, src)
}
func (m *GetResp) XXX_Size() int {
	return xxx_messageInfo_GetResp.Size(m)
}
func (m *GetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetResp proto.InternalMessageInfo

func (m *GetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *GetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *GetResp) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type GetallReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetallReq) Reset()         { *m = GetallReq{} }
func (m *GetallReq) String() string { return proto.CompactTextString(m) }
func (*GetallReq) ProtoMessage()    {}
func (*GetallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{10}
}
func (m *GetallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetallReq.Unmarshal(m, b)
}
func (m *GetallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetallReq.Marshal(b, m, deterministic)
}
func (dst *GetallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetallReq.Merge(dst, src)
}
func (m *GetallReq) XXX_Size() int {
	return xxx_messageInfo_GetallReq.Size(m)
}
func (m *GetallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetallReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetallReq proto.InternalMessageInfo

func (m *GetallReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetallReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *GetallReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

type GetallResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetallResp) Reset()         { *m = GetallResp{} }
func (m *GetallResp) String() string { return proto.CompactTextString(m) }
func (*GetallResp) ProtoMessage()    {}
func (*GetallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{11}
}
func (m *GetallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetallResp.Unmarshal(m, b)
}
func (m *GetallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetallResp.Marshal(b, m, deterministic)
}
func (dst *GetallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetallResp.Merge(dst, src)
}
func (m *GetallResp) XXX_Size() int {
	return xxx_messageInfo_GetallResp.Size(m)
}
func (m *GetallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetallResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetallResp proto.InternalMessageInfo

func (m *GetallResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *GetallResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *GetallResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *GetallResp) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type IncrbyReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Field                *Field   `protobuf:"bytes,4,req,name=field" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrbyReq) Reset()         { *m = IncrbyReq{} }
func (m *IncrbyReq) String() string { return proto.CompactTextString(m) }
func (*IncrbyReq) ProtoMessage()    {}
func (*IncrbyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{12}
}
func (m *IncrbyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrbyReq.Unmarshal(m, b)
}
func (m *IncrbyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrbyReq.Marshal(b, m, deterministic)
}
func (dst *IncrbyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrbyReq.Merge(dst, src)
}
func (m *IncrbyReq) XXX_Size() int {
	return xxx_messageInfo_IncrbyReq.Size(m)
}
func (m *IncrbyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrbyReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncrbyReq proto.InternalMessageInfo

func (m *IncrbyReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *IncrbyReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *IncrbyReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *IncrbyReq) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type IncrbyResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	NewValue             *Field   `protobuf:"bytes,4,opt,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncrbyResp) Reset()         { *m = IncrbyResp{} }
func (m *IncrbyResp) String() string { return proto.CompactTextString(m) }
func (*IncrbyResp) ProtoMessage()    {}
func (*IncrbyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{13}
}
func (m *IncrbyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncrbyResp.Unmarshal(m, b)
}
func (m *IncrbyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncrbyResp.Marshal(b, m, deterministic)
}
func (dst *IncrbyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncrbyResp.Merge(dst, src)
}
func (m *IncrbyResp) XXX_Size() int {
	return xxx_messageInfo_IncrbyResp.Size(m)
}
func (m *IncrbyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IncrbyResp.DiscardUnknown(m)
}

var xxx_messageInfo_IncrbyResp proto.InternalMessageInfo

func (m *IncrbyResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *IncrbyResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *IncrbyResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *IncrbyResp) GetNewValue() *Field {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type DecrbyReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Field                *Field   `protobuf:"bytes,4,req,name=field" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrbyReq) Reset()         { *m = DecrbyReq{} }
func (m *DecrbyReq) String() string { return proto.CompactTextString(m) }
func (*DecrbyReq) ProtoMessage()    {}
func (*DecrbyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{14}
}
func (m *DecrbyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrbyReq.Unmarshal(m, b)
}
func (m *DecrbyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrbyReq.Marshal(b, m, deterministic)
}
func (dst *DecrbyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrbyReq.Merge(dst, src)
}
func (m *DecrbyReq) XXX_Size() int {
	return xxx_messageInfo_DecrbyReq.Size(m)
}
func (m *DecrbyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrbyReq.DiscardUnknown(m)
}

var xxx_messageInfo_DecrbyReq proto.InternalMessageInfo

func (m *DecrbyReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DecrbyReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *DecrbyReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *DecrbyReq) GetField() *Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type DecrbyResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	NewValue             *Field   `protobuf:"bytes,4,opt,name=newValue" json:"newValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecrbyResp) Reset()         { *m = DecrbyResp{} }
func (m *DecrbyResp) String() string { return proto.CompactTextString(m) }
func (*DecrbyResp) ProtoMessage()    {}
func (*DecrbyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{15}
}
func (m *DecrbyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecrbyResp.Unmarshal(m, b)
}
func (m *DecrbyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecrbyResp.Marshal(b, m, deterministic)
}
func (dst *DecrbyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecrbyResp.Merge(dst, src)
}
func (m *DecrbyResp) XXX_Size() int {
	return xxx_messageInfo_DecrbyResp.Size(m)
}
func (m *DecrbyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DecrbyResp.DiscardUnknown(m)
}

var xxx_messageInfo_DecrbyResp proto.InternalMessageInfo

func (m *DecrbyResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *DecrbyResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *DecrbyResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *DecrbyResp) GetNewValue() *Field {
	if m != nil {
		return m.NewValue
	}
	return nil
}

type CompareAndSetReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	New                  *Field   `protobuf:"bytes,4,req,name=new" json:"new,omitempty"`
	Old                  *Field   `protobuf:"bytes,5,req,name=old" json:"old,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetReq) Reset()         { *m = CompareAndSetReq{} }
func (m *CompareAndSetReq) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetReq) ProtoMessage()    {}
func (*CompareAndSetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{16}
}
func (m *CompareAndSetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetReq.Unmarshal(m, b)
}
func (m *CompareAndSetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetReq.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetReq.Merge(dst, src)
}
func (m *CompareAndSetReq) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetReq.Size(m)
}
func (m *CompareAndSetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetReq proto.InternalMessageInfo

func (m *CompareAndSetReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *CompareAndSetReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CompareAndSetReq) GetNew() *Field {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *CompareAndSetReq) GetOld() *Field {
	if m != nil {
		return m.Old
	}
	return nil
}

type CompareAndSetResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Value                *Field   `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetResp) Reset()         { *m = CompareAndSetResp{} }
func (m *CompareAndSetResp) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetResp) ProtoMessage()    {}
func (*CompareAndSetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{17}
}
func (m *CompareAndSetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetResp.Unmarshal(m, b)
}
func (m *CompareAndSetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetResp.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetResp.Merge(dst, src)
}
func (m *CompareAndSetResp) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetResp.Size(m)
}
func (m *CompareAndSetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetResp proto.InternalMessageInfo

func (m *CompareAndSetResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CompareAndSetResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CompareAndSetResp) GetValue() *Field {
	if m != nil {
		return m.Value
	}
	return nil
}

type CompareAndSetnxReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	New                  *Field   `protobuf:"bytes,4,req,name=new" json:"new,omitempty"`
	Old                  *Field   `protobuf:"bytes,5,req,name=old" json:"old,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetnxReq) Reset()         { *m = CompareAndSetnxReq{} }
func (m *CompareAndSetnxReq) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetnxReq) ProtoMessage()    {}
func (*CompareAndSetnxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{18}
}
func (m *CompareAndSetnxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetnxReq.Unmarshal(m, b)
}
func (m *CompareAndSetnxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetnxReq.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetnxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetnxReq.Merge(dst, src)
}
func (m *CompareAndSetnxReq) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetnxReq.Size(m)
}
func (m *CompareAndSetnxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetnxReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetnxReq proto.InternalMessageInfo

func (m *CompareAndSetnxReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetnxReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *CompareAndSetnxReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CompareAndSetnxReq) GetNew() *Field {
	if m != nil {
		return m.New
	}
	return nil
}

func (m *CompareAndSetnxReq) GetOld() *Field {
	if m != nil {
		return m.Old
	}
	return nil
}

type CompareAndSetnxResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Value                *Field   `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompareAndSetnxResp) Reset()         { *m = CompareAndSetnxResp{} }
func (m *CompareAndSetnxResp) String() string { return proto.CompactTextString(m) }
func (*CompareAndSetnxResp) ProtoMessage()    {}
func (*CompareAndSetnxResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{19}
}
func (m *CompareAndSetnxResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompareAndSetnxResp.Unmarshal(m, b)
}
func (m *CompareAndSetnxResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompareAndSetnxResp.Marshal(b, m, deterministic)
}
func (dst *CompareAndSetnxResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompareAndSetnxResp.Merge(dst, src)
}
func (m *CompareAndSetnxResp) XXX_Size() int {
	return xxx_messageInfo_CompareAndSetnxResp.Size(m)
}
func (m *CompareAndSetnxResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompareAndSetnxResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompareAndSetnxResp proto.InternalMessageInfo

func (m *CompareAndSetnxResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *CompareAndSetnxResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *CompareAndSetnxResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CompareAndSetnxResp) GetValue() *Field {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetnxReq struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	Table                *string  `protobuf:"bytes,2,req,name=table" json:"table,omitempty"`
	Key                  *string  `protobuf:"bytes,3,req,name=key" json:"key,omitempty"`
	Fields               []*Field `protobuf:"bytes,4,rep,name=fields" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetnxReq) Reset()         { *m = SetnxReq{} }
func (m *SetnxReq) String() string { return proto.CompactTextString(m) }
func (*SetnxReq) ProtoMessage()    {}
func (*SetnxReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{20}
}
func (m *SetnxReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetnxReq.Unmarshal(m, b)
}
func (m *SetnxReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetnxReq.Marshal(b, m, deterministic)
}
func (dst *SetnxReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetnxReq.Merge(dst, src)
}
func (m *SetnxReq) XXX_Size() int {
	return xxx_messageInfo_SetnxReq.Size(m)
}
func (m *SetnxReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetnxReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetnxReq proto.InternalMessageInfo

func (m *SetnxReq) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetnxReq) GetTable() string {
	if m != nil && m.Table != nil {
		return *m.Table
	}
	return ""
}

func (m *SetnxReq) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *SetnxReq) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

type SetnxResp struct {
	Seqno                *int64   `protobuf:"varint,1,req,name=seqno" json:"seqno,omitempty"`
	ErrCode              *int32   `protobuf:"varint,2,req,name=errCode" json:"errCode,omitempty"`
	Version              *int64   `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetnxResp) Reset()         { *m = SetnxResp{} }
func (m *SetnxResp) String() string { return proto.CompactTextString(m) }
func (*SetnxResp) ProtoMessage()    {}
func (*SetnxResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_protocol_865f75d71be546b8, []int{21}
}
func (m *SetnxResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetnxResp.Unmarshal(m, b)
}
func (m *SetnxResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetnxResp.Marshal(b, m, deterministic)
}
func (dst *SetnxResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetnxResp.Merge(dst, src)
}
func (m *SetnxResp) XXX_Size() int {
	return xxx_messageInfo_SetnxResp.Size(m)
}
func (m *SetnxResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetnxResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetnxResp proto.InternalMessageInfo

func (m *SetnxResp) GetSeqno() int64 {
	if m != nil && m.Seqno != nil {
		return *m.Seqno
	}
	return 0
}

func (m *SetnxResp) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *SetnxResp) GetVersion() int64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Value)(nil), "proto.value")
	proto.RegisterType((*Field)(nil), "proto.field")
	proto.RegisterType((*PingReq)(nil), "proto.ping_req")
	proto.RegisterType((*PingResp)(nil), "proto.ping_resp")
	proto.RegisterType((*DelReq)(nil), "proto.del_req")
	proto.RegisterType((*DelResp)(nil), "proto.del_resp")
	proto.RegisterType((*SetReq)(nil), "proto.set_req")
	proto.RegisterType((*SetResp)(nil), "proto.set_resp")
	proto.RegisterType((*GetReq)(nil), "proto.get_req")
	proto.RegisterType((*GetResp)(nil), "proto.get_resp")
	proto.RegisterType((*GetallReq)(nil), "proto.getall_req")
	proto.RegisterType((*GetallResp)(nil), "proto.getall_resp")
	proto.RegisterType((*IncrbyReq)(nil), "proto.incrby_req")
	proto.RegisterType((*IncrbyResp)(nil), "proto.incrby_resp")
	proto.RegisterType((*DecrbyReq)(nil), "proto.decrby_req")
	proto.RegisterType((*DecrbyResp)(nil), "proto.decrby_resp")
	proto.RegisterType((*CompareAndSetReq)(nil), "proto.compare_and_set_req")
	proto.RegisterType((*CompareAndSetResp)(nil), "proto.compare_and_set_resp")
	proto.RegisterType((*CompareAndSetnxReq)(nil), "proto.compare_and_setnx_req")
	proto.RegisterType((*CompareAndSetnxResp)(nil), "proto.compare_and_setnx_resp")
	proto.RegisterType((*SetnxReq)(nil), "proto.setnx_req")
	proto.RegisterType((*SetnxResp)(nil), "proto.setnx_resp")
	proto.RegisterEnum("proto.ValueType", ValueType_name, ValueType_value)
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_protocol_865f75d71be546b8) }

var fileDescriptor_protocol_865f75d71be546b8 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcf, 0x6f, 0xd3, 0x30,
	0x18, 0x95, 0xe3, 0xa4, 0x49, 0xbe, 0x4e, 0x53, 0x64, 0xc6, 0x64, 0x21, 0x84, 0x22, 0x8b, 0x43,
	0xe0, 0xb0, 0xc3, 0x2e, 0x48, 0x5c, 0x91, 0x90, 0xc6, 0x81, 0x83, 0xf7, 0xe3, 0x5a, 0x65, 0x8b,
	0x89, 0x22, 0x5c, 0x3b, 0x4b, 0x4c, 0x46, 0x91, 0x38, 0x20, 0xf1, 0xe3, 0x0f, 0x40, 0xfc, 0xbf,
	0x28, 0x4e, 0x9a, 0x75, 0xa5, 0x4c, 0x20, 0xb2, 0x8d, 0x53, 0xfd, 0xfc, 0xbe, 0xfa, 0x7b, 0xef,
	0xa5, 0xfd, 0x62, 0xd8, 0x2e, 0x2b, 0x6d, 0xf4, 0x99, 0x96, 0x7b, 0x76, 0x41, 0x3c, 0xfb, 0xc1,
	0xbe, 0x20, 0xf0, 0x9a, 0x54, 0xbe, 0x13, 0x24, 0x06, 0xc7, 0x18, 0x8a, 0x62, 0x27, 0xd9, 0xde,
	0x8f, 0xba, 0xa2, 0xbd, 0x93, 0x96, 0x39, 0x5a, 0x94, 0x82, 0x3b, 0xc6, 0x10, 0x02, 0x6e, 0x73,
	0xa0, 0x0c, 0x75, 0x62, 0x94, 0x60, 0x6e, 0xd7, 0x64, 0x07, 0xbc, 0xe6, 0xb8, 0xdd, 0xc4, 0x31,
	0x4a, 0x5c, 0xde, 0x01, 0xb2, 0x0b, 0x93, 0xe6, 0xa5, 0xd4, 0xa9, 0xa1, 0x6e, 0x8c, 0x12, 0xc4,
	0x7b, 0x44, 0x28, 0xf8, 0xcd, 0xa1, 0xa9, 0x0a, 0x95, 0x53, 0x2f, 0x46, 0x49, 0xc8, 0x97, 0x90,
	0x3d, 0x03, 0xef, 0x4d, 0x21, 0x64, 0xd6, 0x36, 0x51, 0xe9, 0x5c, 0x50, 0x64, 0x79, 0xbb, 0x26,
	0x0f, 0x00, 0x35, 0xb6, 0xeb, 0x74, 0x7f, 0xab, 0x57, 0x66, 0x35, 0x73, 0xd4, 0xb0, 0x04, 0x82,
	0xb2, 0x50, 0xf9, 0xac, 0x12, 0xe7, 0xe4, 0x21, 0x84, 0xa6, 0x98, 0x8b, 0xda, 0xa4, 0xf3, 0xd2,
	0x1e, 0x80, 0xf9, 0xe5, 0x06, 0x7b, 0x02, 0x61, 0x5f, 0x59, 0x97, 0x57, 0x4b, 0x9d, 0xf5, 0xd2,
	0x14, 0xfc, 0x4c, 0x48, 0x7b, 0xe6, 0x0e, 0x78, 0xb5, 0x38, 0x57, 0xda, 0x26, 0x83, 0x79, 0x07,
	0xac, 0x11, 0x51, 0xd5, 0x85, 0x56, 0xfd, 0x97, 0x97, 0xb0, 0xad, 0x37, 0xe9, 0xa9, 0x14, 0x14,
	0xc7, 0x4e, 0x12, 0xf2, 0x0e, 0x90, 0x08, 0xf0, 0x5b, 0xb1, 0xa0, 0xae, 0xdd, 0x6b, 0x97, 0xec,
	0x39, 0x04, 0x5d, 0x8b, 0xba, 0xfc, 0x7d, 0x0f, 0x51, 0x55, 0x2f, 0x74, 0x26, 0xa8, 0x13, 0x3b,
	0x89, 0xc7, 0x97, 0x90, 0x7d, 0x43, 0xe0, 0xd7, 0xc2, 0xdc, 0xa4, 0x3e, 0xf2, 0x18, 0x26, 0xf6,
	0x81, 0xd4, 0xd4, 0x8b, 0xf1, 0x4a, 0xf0, 0x76, 0x93, 0xf7, 0x1c, 0x3b, 0x82, 0xa0, 0x13, 0xf2,
	0xf7, 0x2e, 0x56, 0x35, 0xe2, 0x2b, 0x1a, 0xd9, 0x0c, 0xfc, 0xfc, 0x5a, 0x7b, 0x83, 0x09, 0x67,
	0x83, 0x09, 0x7c, 0x69, 0x62, 0x77, 0x30, 0xe1, 0xc6, 0x38, 0x09, 0x07, 0xd9, 0x1f, 0x20, 0xc8,
	0x47, 0x97, 0xbd, 0x12, 0x99, 0x7b, 0x4d, 0x64, 0xaf, 0x00, 0x72, 0x61, 0x52, 0x29, 0xff, 0xdd,
	0x1f, 0xfb, 0x08, 0xd3, 0xe1, 0xac, 0x3b, 0xb0, 0xa2, 0x00, 0x0a, 0x75, 0x56, 0x9d, 0x2e, 0x46,
	0x78, 0x54, 0xac, 0x1f, 0x00, 0xf6, 0x37, 0xb8, 0xde, 0xb0, 0xa3, 0xd8, 0x27, 0x04, 0xd3, 0xa1,
	0xe1, 0xa8, 0x7e, 0x13, 0x08, 0x94, 0xb8, 0xb0, 0xe3, 0xce, 0x8e, 0xac, 0x75, 0x01, 0x03, 0xdb,
	0x7a, 0xce, 0xc4, 0x2d, 0x7b, 0x1e, 0x1a, 0xde, 0x91, 0xe7, 0xef, 0x08, 0xee, 0x9d, 0xe9, 0x79,
	0x99, 0x56, 0x62, 0x96, 0xaa, 0x6c, 0x56, 0x8f, 0xf2, 0xe7, 0x7c, 0x04, 0x58, 0x89, 0x8b, 0x8d,
	0xde, 0x5b, 0xa2, 0xe5, 0xb5, 0xcc, 0xa8, 0xb7, 0x89, 0xd7, 0x32, 0x63, 0x9f, 0x11, 0xec, 0xfc,
	0xaa, 0x6a, 0xd4, 0x88, 0x58, 0xff, 0x72, 0xdc, 0x98, 0x4f, 0x47, 0xb1, 0x1f, 0x08, 0xee, 0xaf,
	0xc9, 0x50, 0xef, 0xff, 0x83, 0x78, 0xbe, 0x22, 0xd8, 0xdd, 0xa4, 0xeb, 0xd6, 0x03, 0xd2, 0x10,
	0x8e, 0x95, 0xc9, 0x9f, 0x8d, 0xa5, 0x13, 0x80, 0x9b, 0x30, 0xfb, 0xf4, 0x10, 0xc2, 0xe1, 0x42,
	0x44, 0x7c, 0xc0, 0xaf, 0x0b, 0x19, 0x21, 0x02, 0x30, 0xe9, 0xee, 0x30, 0x91, 0x43, 0xa6, 0xe0,
	0x1f, 0x28, 0x23, 0x72, 0x51, 0x45, 0x98, 0x6c, 0x41, 0x70, 0x5c, 0xf4, 0xc8, 0x25, 0x21, 0x78,
	0xf6, 0x0e, 0x14, 0x79, 0x5d, 0x55, 0x93, 0x16, 0x32, 0x8b, 0x26, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x4c, 0xdd, 0xc7, 0xc0, 0x98, 0x09, 0x00, 0x00,
}
